app:
  grpc:
    server:
      host: localhost
      port: 44044
    client:
      notification-service:
        host: localhost
        port: 44045

  auth-service:
    token-ttl: 1h
    token-secret-key: ""

  postgres:
    host: localhost
    port: 5432
    database: auth_grpc

  redis:
    host: localhost
    port: 6379
    database: 0